describe("Pruebas en automationexercise", () => {
 it.skip('Registrar usuario', () => {
 cy.visit('https://automationexercise.com/')
 cy.get('section[style="height: auto !important;"] > .container > .row')
 cy.get('.shop-menu > .nav > :nth-child(4) > a').click()
 cy.get('[data-qa="signup-name"]').type('Manuelgonzalez')
 cy.get('[data-qa="signup-email"]').type('pericodelospalotess@gmail.com')
 cy.get('[data-qa="signup-button"]').click()
 cy.get('[data-qa="password"]').type('raul123')
 cy.get('[data-qa="days"]').select('5')
 cy.get('[data-qa="months"]').select('August')
 cy.get('[data-qa="years"]').select('1995')
 cy.get('#id_gender1').click()
 cy.get('[data-qa="first_name"]').type('benalmadena')
 cy.get('[data-qa="last_name"]').type('Málaga')
 cy.get('[data-qa="country"]').select('United States')
 cy.get('[data-qa="state"]').type('Washington')
 cy.get('[data-qa="city"]').type('Washington')
 cy.get('[data-qa="zipcode"]').type('1234')
 cy.get('[data-qa="mobile_number"]').type('123456789')
 cy.get('[data-qa="address"]').type('dirección de prueba')
 cy.get('[data-qa="create-account"]').click()
 cy.get('[data-qa="continue-button"]').click()
 cy.get(':nth-child(10) > a').should('be.visible')
 cy.get('.shop-menu > .nav > :nth-child(5) > a').click()
 cy.get('b').should('be.visible')
 cy.get('[data-qa="continue-button"]').click()

 })
 it.skip('Login con usuario y contraseña correcto', () => {
    cy.visit('https://automationexercise.com/')
    cy.get('section[style="height: auto !important;"] > .container > .row').should('be.visible')
    cy.get('.shop-menu > .nav > :nth-child(4) > a').click()
    cy.get('.login-form > h2').should('be.visible')
    cy.get('[data-qa="login-email"]').type('tete.manolo95@gmail.com')
    cy.get('[data-qa="login-password"]').type('raul123')
    cy.get('[data-qa="login-button"]').click()
    cy.get(':nth-child(10) > a').should('be.visible')
    cy.get('.shop-menu > .nav > :nth-child(5) > a').click()
    cy.get('.shop-menu > .nav > :nth-child(5) > a').should('be.visible')

})
it.skip('Login con usuario y contraseña correcto', () => {
    cy.visit('https://automationexercise.com/')
    cy.get('section[style="height: auto !important;"] > .container > .row').should('be.visible')
    cy.get('.shop-menu > .nav > :nth-child(4) > a').click()
    cy.get('.login-form > h2').should('be.visible')
    cy.get('[data-qa="login-email"]').type('tetemanolo95@gmail.com')
    cy.get('[data-qa="login-password"]').type('aul123')
    cy.get('[data-qa="login-button"]').click()
    cy.get('.login-form > form > p').should('be.visible')
})
it.skip('Hacer Log out', () => {
    cy.visit('https://automationexercise.com/')
    cy.get('section[style="height: auto !important;"] > .container > .row').should('be.visible')
    cy.get('.shop-menu > .nav > :nth-child(4) > a').click()
    cy.get('.login-form > h2').should('be.visible')
    cy.get('[data-qa="login-email"]').type('tete.manolo95@gmail.com')
    cy.get('[data-qa="login-password"]').type('raul123')
    cy.get('[data-qa="login-button"]').click()
    cy.get(':nth-child(10) > a').should('be.visible')
    cy.get('.shop-menu > .nav > :nth-child(4) > a').click()
    cy.get('body').should('be.visible')

})
it.skip('Registrar un usuario con un email existente', () => {
    cy.visit('https://automationexercise.com/')
    cy.get('section[style="height: auto !important;"] > .container > .row').should('be.visible')
    cy.get('.shop-menu > .nav > :nth-child(4) > a').click()
    cy.get('.signup-form > h2').should('be.visible')
    cy.get('[data-qa="signup-name"]').type('manuel')
    cy.get('[data-qa="signup-email"]').type('tete.manolo95@gmail.com')
    cy.get('[data-qa="signup-button"]').click()
    cy.get('.signup-form > form > p').should('be.visible')
})
it.skip('Contactanos', () => {
    cy.visit('https://automationexercise.com/')
    cy.get('section[style="height: auto !important;"] > .container > .row').should('be.visible')
    cy.get(':nth-child(8) > a > .fa').click()
    cy.get('div.contact-form > .title').should('be.visible')
    cy.get('[data-qa="name"]').type('manuel')
    cy.get('[data-qa="email"]').type('tete.manolo95@gmail.com')
    cy.get('[data-qa="subject"]').type('test')
    cy.get('[data-qa="message"]').type('this is a test')
    cy.get(':nth-child(6) > .form-control').click()
    cy.get('[data-qa="submit-button"]').click()
    cy.get('.status').should('be.visible')
    cy.get('span').click()
    cy.get('section[style="height: auto !important;"] > .container > .row').should('be.visible')


})
it.skip('verificar la página de test cases', () => {
    cy.visit('https://automationexercise.com/')
    cy.get('section[style="height: auto !important;"] > .container > .row').should('be.visible')
    cy.get(':nth-child(5) > a > .fa').click()
    cy.get('body').should('be.visible')
})
it.skip('verificar todos los productos y la página de detalles de los productos', () => {
    cy.visit('https://automationexercise.com/')
    cy.get('section[style="height: auto !important;"] > .container > .row').should('be.visible')
    cy.get('a > .material-icons').click()
    cy.get('section[style="height: auto !important;"] > .container > .row').should('be.visible')
    cy.get('.features_items').should('be.visible')
    cy.get(':nth-child(3) > .product-image-wrapper > .choose > .nav > li > a').click()
    cy.get('.product-information > h2').should('be.visible')
    cy.get('.product-information > :nth-child(8)').should('be.visible')
})
it.skip('Buscador de productos', () => {
    cy.visit('https://automationexercise.com/')
    cy.get('section[style="height: auto !important;"] > .container > .row').should('be.visible')
    cy.get('a > .material-icons').click()
    cy.get('section[style="height: auto !important;"] > .container > .row').should('be.visible')
    cy.get('#search_product').type('Blue Top')
    cy.get('#submit_search > .fa').click()
    cy.get('.features_items > .col-sm-4').should('be.visible')
    cy.get('body').should('be.visible')
})
it('Verificar la suscripción en la página principal', () => {
    cy.visit('https://automationexercise.com/')
    cy.get('section[style="height: auto !important;"] > .container > .row').should('be.visible')
    cy.get('.single-widget > h2').should('be.visible')
    cy.get('#susbscribe_email').type('tete.manolo95@gmail.com')
    cy.get('#subscribe > .fa').click()
    cy.get('.alert-success').should('be.visible')
})
})