describe('template spec', () => {
  it('test de login valido', () => {
    cy.visit('https://the-internet.herokuapp.com/')
    cy.get(':nth-child(21) > a').click()
    cy.get('#username').type("tomsmith")
    cy.get('#password').type("SuperSecretPassword!")
    cy.get('.radius').click()
    cy.get('#flash').contains("You logged into a secure area!")
  })
  it('test de login invalido 1', () => {
    cy.visit('https://the-internet.herokuapp.com/')
    cy.get(':nth-child(21) > a').click()
    cy.get('#username').type("")
    cy.get('#password').type("SuperSecretPassword!")
    cy.get('.radius').click()
    cy.get('#flash').contains("You logged into a secure area!")
  })
  it('test de login invalido 2', () => {
    cy.visit('https://the-internet.herokuapp.com/')
    cy.get(':nth-child(21) > a').click()
    cy.get('#username').type("tomsmith")
    cy.get('#password').type("")
    cy.get('.radius').click()
    cy.get('#flash').contains("You logged into a secure area!")
  })
  it('test de login invalido 3', () => {
    cy.visit('https://the-internet.herokuapp.com/')
    cy.get(':nth-child(21) > a').click()
    cy.get('#username').type("tomsmi")
    cy.get('#password').type("SuperSecretPassword!")
    cy.get('.radius').click()
    cy.get('#flash').contains("You logged into a secure area!")
  })
})
